"""empty message

Revision ID: f81be83eabd2
Revises: 0d9c57d9f6d3
Create Date: 2024-03-09 15:20:02.026345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81be83eabd2'
down_revision: Union[str, None] = '0d9c57d9f6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_salt', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
