name: Fastapi backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend_news_data_processor

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: gt005_test
          POSTGRES_PASSWORD: gt005_test_db_password
          POSTGRES_DB: api_service_test_db
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Load environment variables from .env.example
      run: |
        set -a
        source <(cat .env.example | sed -e '/^#/d;/^\s*$/d')
        set +a

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check import sorting with isort
      run: |
        isort . --check-only

    - name: Test with pytest
      run: |
        export PYTHONPATH=$(pwd)
        pytest
