name: Frontend React Service CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
  
    defaults:
      run:
        working-directory: ./frontend_service

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies (React Service)
      run: yarn install

    - name: Run tests (React Service)
      run: yarn test

    - name: Docker login (Docker Hub)
      if: ${{ success() }}
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build & Push Docker Image
      if: ${{ success() }}
      uses: docker/build-push-action@v4
      with:
        context: ../..
        file: ./FrontendDockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/news_aggregator_frontend:${{ github.sha }}
