name: Frontend React Service CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
  
    defaults:
      run:
        working-directory: ./frontend_service

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies (React Service)
      run: yarn install

    - name: Run tests (React Service)
      run: yarn test
