name: Parser Services CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./website_parsing_service

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies (Parser Services)
      run: yarn install

    - name: Check ESLint
      run: yarn eslint . --ext .js,.jsx,.ts,.tsx

    - name: Check Prettier
      run: yarn prettier --check .

    - name: Run tests (Parser Services)
      run: yarn test

    - name: Docker login (Docker Hub)
      if: ${{ success() }}
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build & Push Docker Image (Website parsing)
      if: ${{ success() }}
      uses: docker/build-push-action@v4
      with:
        context: ../..
        file: ../RbcParserDockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/news_aggregator_website_parser:${{ github.sha }}

    - name: Build & Push Docker Image (Telegram parser)
      if: ${{ success() }}
      uses: docker/build-push-action@v4
      with:
        context: ../..
        file: ../TelegramParserDockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/news_aggregator_telegram_parser:${{ github.sha }}
