name: Parcer Services CI

on:
  push:
    paths:
      - 'website_parsing_service/**'
  pull_request:
    paths:
      - 'website_parsing_service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.1'

    - name: Install dependencies (JavaScript Service)
      run: cd website_parsing_service && yarn install

    - name: Run tests (JavaScript Service)
      run: cd website_parsing_service && yarn test
