name: Parcer Services CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./website_parsing_service

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies (Parcer Services)
      run: yarn install

    - name: Check ESLint
      run: yarn eslint . --ext .js,.jsx,.ts,.tsx

    - name: Check Prettier
      run: yarn prettier --check .

    - name: Run tests (Parcer Services)
      run: yarn test
